---

- hosts: localhost

  vars:
    rssdler_download: https://rssdler.googlecode.com/files/rssdler-0.4.2.tar.gz

  tasks:
    - name: install pip
      easy_install: name=pip

    - name: install python feedparser
      yum:
        name="python-feedparser"
        state=latest

    - name: install python mechanize
      pip:
        name=mechanize
        state=latest

    - name: download rssdler python script
      get_url:
        url={{rssdler_download}}
        dest=/tmp/rssdler.tar.gz

    - name: extract rssdler
      unarchive:
        src=/tmp/rssdler.tar.gz
        dest=/opt
        copy=no
        creates=rssdler042

    - name: create rssdler daemon user
      user:
        name=rssdler
        system=yes

    - name: create rssdler directories
      file:
        path=/var/lib/rssdler/{{item}}
        state=directory
        mode=0755
        owner=rssdler
        group=rssdler
      with_items:
        - download
        - workingdir
        - logs

    - name: run the python installer
      command: /usr/bin/python /opt/rssdler042/setup.py install
        chdir=/opt/rssdler042

    - name: move configuration file to working dir
      command: mv rssdler.conf /var/lib/rssdler/workingdir/rssdler.conf

    - name: set file permissions
      file:
        path=/var/lib/rssdler/rssdler.conf
        owner=rssdler
        group=rssdler