---

#
# use ansible to install the dockerized nas services onto a machine
#
# please install ansible on the machine to execute this setup script
# install ansible following the official ansible documentation:
# http://docs.ansible.com/intro_installation.html
#
# run the setup script with the following command line
# sudo ansible-playbook -c local setup.yml

- hosts: localhost

  tasks:
    - name: import setup variables
      include_vars: setup_vars.yml

    - name: setup docker repository
      copy:
        src=./files/docker.repo
        dest=/etc/yum.repos.d/docker.repo
        owner=root
        group=root
        mode=644
        backup=no

    - name: install docker
      yum:
        name=docker-engine
        state=latest

    - name: copy docker defaults
      template:
        src=files/docker.j2
        dest=/etc/sysconfig/docker
        owner=root
        group=root
        mode=0644

    - name: enable docker
      service:
        name=docker
        state=started
        enabled=yes

    - name: create etcd user account
      user:
        name=etcd
        createhome=no
        system=yes
        shell=/bin/nologin
        state=present

    - name: download etcd for docker self configuration
      get_url: 
        url={{etcd_download}}
        dest=/tmp/etcd.tar.gz

    - name: extract etcd
      unarchive: 
        src=/tmp/etcd.tar.gz dest=/opt

    - name: create softlink for etcd
      file:
        file: 
          src=/opt/{{etcd_version}} 
          dest=/opt/etcd 
          owner=etcd 
          group=etcd 
          state=link
          force=yes

    - name: copy service file
      template:
        src=files/etcd.service.j2
        dest=/etc/systemd/system
        owner=root
        group=root
        mode=0644

    - name: enable and start etcd
      service:
        name=etcd
        state=started
        enabled=yes

    - name: copy dnas environment file for systemd
      template:
        src=files/dnas.j2
        dest=/etc/sysconfig/dnas
        owner=root
        group=root
        mode=0644

    - name: setup rssdler docker container
      include: ../container/rssdler/setup.yml

    - name: setup plex docker container
      include: ../container/plex/setup.yml

    - name: setup sabnzbd docker container
      include: ../container/sabnzbd/setup.yml

    - name: setup couchpotato docker container
      include: ../container/couchpotato/setup.yml

    - name: setup sickbeard docker container
      include: ../container/sickbeard/setup.yml


