---

#
# use ansible to install the dockerized nas services onto a machine
#
# please install ansible on the machine to execute this setup script
# install ansible following the official ansible documentation:
# http://docs.ansible.com/intro_installation.html
#
# run the setup script with the following command line
# sudo ansible-playbook -c local setup.yml

- hosts: localhost

  tasks:
    - name: import setup variables
      include_vars: setup_vars.yml

    - name: setup docker repository
      copy:
        src=./files/docker.repo
        dest=/etc/yum.repos.d/docker.repo
        owner=root
        group=root
        mode=644
        backup=no

    - name: install docker
      yum:
        name=docker-engine
        state=latest

    - name: enable docker
      service:
        name=docker
        state=started
        enabled=yes

    - name: get some debug info
      debug: var=rssdler_enabled
      debug: var=rssdler_download
      debug: var=rssdler_working
      debug: var=rssdler_logs

