---

#
# use ansible to install the dockerized nas services onto a machine
#
# please install ansible on the machine to execute this setup script
# install ansible following the official ansible documentation:
# http://docs.ansible.com/intro_installation.html
#
# run the setup script with the following command line
# sudo ansible-playbook -c local setup.yml

- hosts: localhost

  tasks:
    - name: import setup variables
      include_vars: setup_vars.yml

#
# install and configure docker
#

    - name: setup docker repository
      copy:
        src=./files/docker.repo
        dest=/etc/yum.repos.d/docker.repo
        owner=root
        group=root
        mode=644
        backup=no

    - name: install docker
      yum:
        name=docker-engine
        state=latest

    - name: copy docker defaults
      template:
        src=files/docker.j2
        dest=/etc/sysconfig/docker
        owner=root
        group=root
        mode=0644

    - name: copy docker service file due to docker defaults not workingf
      template:
        src=files/docker.service.j2
        dest=/usr/lib/systemd/system/docker.service
        owner=root
        group=root
        mode=0644

#
# setup dnas defaults
#

    - name: copy dnas environment file for systemd
      template:
        src=files/dnas.j2
        dest=/etc/sysconfig/dnas
        owner=root
        group=root
        mode=0644

    - name: copy etcd environment file for systemd
      template:
        src=files/etcd.j2
        dest=/etc/sysconfig/etcd
        owner=root
        group=root
        mode=0644

    - name: create etcd user account
      user:
        name=etcd
        createhome=no
        system=yes
        shell=/bin/nologin
        state=present

    - name: create dnas base directory
      file:
        path={{dnas_base}}
        owner=root
        group=root
        mode=0755
        state=directory

    - name: create docker base directory
      file:
        path={{docker_base}}
        owner=root
        group=root
        mode=0700
        state=directory

    - name: create etcd base directory
      file:
        path={{etcd_base}}
        owner=etcd
        group=etcd
        mode=0755
        state=directory

    - name: enable docker
      service:
        name=docker
        state=started
        enabled=yes


#
# could be done via etcd rpm!
#

    - name: download etcd for docker self configuration
      get_url:
        url={{etcd_download}}
        dest=/tmp/etcd.tar.gz

    - name: extract etcd
      unarchive:
        src=/tmp/etcd.tar.gz dest=/opt

    - name: create softlink for etcd
      file:
        src=/opt/{{etcd_version}}
        dest={{etcd_install}}
        owner=etcd
        group=etcd
        state=link
        force=yes

    - name: copy service file
      template:
        src=files/etcd.service.j2
        dest=/etc/systemd/system/etcd.service
        owner=root
        group=root
        mode=0755

    - name: copy etcd profile script
      template:
        src=files/etcd.profile.j2
        dest=/etc/profile.d/etcd.sh
        owner=root
        group=root
        mode=0644

    - name: enable and start etcd
      service:
        name=etcd
        state=started
        enabled=yes

#
# could be done via etcd rpm!
#


    - name: copy the dnas scripts
      template:
        src=../scripts
        dest={{dnas_scripts}}
        owner=root
        group=root
        mode=0755
        directory_mode=yes

#
# compile jsson - a json parser cli
#

    - name: install jansson devel libraries
      yum:
        name={{item}}
        state=latest
      with_items:
        - jansson-devel
        - gcc

    - name: clone jshon to parse jsson output in bash
      git:
        repo={{jshon_download}}
        dest=/tmp/jshon

    - name: compile and install jshon
      command: make && make install chdir=/tmp/jshon

    - name: remove jshon build dependencies
      command: yum autoremove -y {{item}}
      with_items:
        - gcc
        - jansson-devel

#
# install socat to access the docker socket via bash
#

    - name: install socat
      yum:
        name=socat
        state=latest

#
# setup the different docker containers
#

    - name: setup rssdler docker container
      include: ../container/rssdler/setup.yml

    - name: setup plex docker container
      include: ../container/plex/setup.yml

    - name: setup sabnzbd docker container
      include: ../container/sabnzbd/setup.yml

    - name: setup couchpotato docker container
      include: ../container/couchpotato/setup.yml

    - name: setup sickbeard docker container
      include: ../container/sickbeard/setup.yml

    - name: setup nzbtomedia docker container
      include: ../container/nzbtomedia/setup.yml

    - name: setup library docker container
      include: ../container/library/setup.yml

